### ISSUE TITLE
OMNI AUTHの実験

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#14]
- 認証の実験を行う
- TwitterとFacebook

**Comment by tatsuosakurai** [comment]
そういえばちょうど、WEBDBPressにじゅんさんとけいさんが記事かいてましたね。

**Comment by vestige** [comment]
TW: https://dev.twitter.com/apps/new
FB: http://www.facebook.com/developers/createapp.php

**Comment by vestige** [comment]
コミットしたー。
twitterの認証はうまくいったよ。

**Comment by vestige** [comment]
2人に確認してもらってからにする。

**Comment by vestige** [comment]
確認してもらった。おしまい。
