### ISSUE TITLE
OmniAuthを1.0にする

### ISSUE THREAD

**Issue by tatsuosakurai** [vestige/tkbb#19]
そういえば1.0出たんですよねえ。ひとまず後回しでいいと思ってますが。

"[omniauth][ruby] OmniAuth 1.0に対応する - fix A moment" http://aereal.hateblo.jp/entry/2011/11/08/033117

**Comment by gardentree** [comment]
#21 で対応しました。

**Comment by tatsuosakurai** [comment]
あざっす！
