### ISSUE TITLE
herokuにアプリケーションを載せる

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#21]
現状の動く状態でまずはのせてみる

**Comment by gardentree** [comment]
1. ローカルで動作させる場合、環境変数(ARM_TWITTER_CONSUMER_KEY,ARM_TWITTER_CONSUMER_SECRET)の設定が必要です(powを使用している場合は、.powenvで設定)。
2. herokuに乗せるには、git構成を変える必要があります > 要検討
3. omniauthの最新版に処理を合わせました。
