### ISSUE TITLE
2月のオフライン勉強会

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#22]
# やりたいこと
## 参加スタイルの確認
- 1人1人が思うこのプロジェクトに対する価値について話す。1時間から1時間半ぐらい。
- このプロジェクトでやりたいことを洗い出す。30分ぐらい。
## 開発
- 最小限の機能を開発する。2,3時間ぐらいかな？

**Comment by gardentree** [comment]
会のファシリテートしたいです！

**Comment by vestige** [comment]
おっ、お願いしますっ！！

**Comment by tatsuosakurai** [comment]
ファシられたいですっ！！

**Comment by vestige** [comment]
ファシられた！おしまい。
