### ISSUE TITLE
Rails3.1にアップデートする

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#25]
- erb の haml化
- compass 
- rspec

それぞれを入れる
2/6月曜日のオンラインで話す

**Comment by tatsuosakurai** [comment]
ついでに、1.9.2-p290にしたい

**Comment by vestige** [comment]
アップデートしたら、Gemfile.lockがこんな風になったんだけど、変更してもいいのかな？

(削除) pg (0.13.0)
(追加) pg (0.13.1)
