### ISSUE TITLE
TOP画面の右下にTWのタイムラインを表示する

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#28]
- ボルダリングに関するツィート情報や#tkbbのハッシュタグをまとめて表示しておきたい
- TwitterのBotを用意する?

! 仕組みの話
- どうやって定期的に動かすの？
- Dripのサンプルとか使えるのかな？

**Comment by tatsuosakurai** [comment]
https://twitter.com/about/resources/widgets/widget_search

ここで楽勝でしたｗ

<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>

<script>
new TWTR.Widget({
  version: 2,
  type: 'search',
  search: '#tkbb',
  interval: 30000,
  title: '#tkbb に関するツイート',
  subject: 'WE CLIMB!',
  width: 250,
  height: 300,
  theme: {
    shell: {
      background: '#8ec1da',
      color: '#ffffff'
    },
    tweets: {
      background: '#ffffff',
      color: '#444444',
      links: '#1985b5'
    }
  },
  features: {
    scrollbar: false,
    loop: true,
    live: true,
    behavior: 'default'
  }
}).render().start();
</script>
