### ISSUE TITLE
今日の宿題

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#5]
rvm gemsetsを作るとパス毎にRubyのバージョンができるらしい。

**Comment by vestige** [comment]
railsの復習→なんとなくした。

**Comment by vestige** [comment]
wikiのセキュリティ周りの設定→お金払えばできる

**Comment by vestige** [comment]
googleのマップのAPIを調べておく→#7 で決める。

**Comment by tatsuosakurai** [comment]
自分の環境で動くようにする。（gemsetsなど用意する）

**Comment by vestige** [comment]
gemset
- http://d.hatena.ne.jp/nashiwater/20110211/1297395132
- http://d.hatena.ne.jp/Umeyashiki/20101120/1290265604

**Comment by tatsuosakurai** [comment]


**Comment by tatsuosakurai** [comment]
- 環境作り
  *\* 参考："デザイナーも１時間でツイッターサービスを作ろう！（準備編） - KUROIGAMEN(黒い画面)" http://kuroigamen.com/34

*\* ruby 1.9.2 を最新にした
rvm use 1.9.2

> WARN: ruby ruby-1.9.2-p180 is not installed.
> To install do: 'rvm install ruby-1.9.2-p180'
> rvm uninstall ruby-1.9.2-p136
> rvm install 1.9.2

*\* arm 用の gemset 作成
rvm gemset create project_arms 
rvm gemset use 'project_arms'

bundle install
rails s
OK!

**Comment by tatsuosakurai** [comment]
あれ？これはcloseでよい？（僕はOKです

**Comment by vestige** [comment]
gemsetがまだできてないや。それができたら、closeだね。
櫻井くんはつくったの？

**Comment by tatsuosakurai** [comment]
あ、そうだ、すみませんー、書き忘れました。

ええと、.rvmrc内に "rvm use ruby-1.9.2-p180@project_arms" と書いてしまったので、
project_armsというgemsetsを作ってもらえるとスムーズにいくと思います＾＾；
rubyのバージョンは ruby-1.9.2-p180 であってます？

gemset作るのは
rvm gemset create project_arms 
↑を実行するだけでOKかな。

**Comment by tatsuosakurai** [comment]
僕の勘違いです。gemset不要。
