### ISSUE TITLE
DBを用意して、入力されたものを登録できるようにする

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#6]
はじめにつくったページの入力内容をDBに登録
もし登録されていたら、登録はしない
submitした先でDBに登録されたデータを表示する

**Comment by vestige** [comment]
僕がRailsになれるようにするための準備運動。

**Comment by vestige** [comment]
訂正、MongoDBを使ってみる。

これをサンプルに他のユースケースから実装がイメージできたらOK

**Comment by 1syo** [comment]
https://github.com/RailsApps/rails3-mongoid-omniauth/wiki/Tutorial
土曜日にこのチュートリアルやってみませんか?

**Comment by vestige** [comment]
いいと思うよ。時間割を考えておかないとね。

**Comment by tatsuosakurai** [comment]
とりあえず、作り慣れているもので作る方針
DB は RDBMS (開発はSQLite3)
あとで別ストーリーにして Mongo に変えてもよい。

**Comment by tatsuosakurai** [comment]
当初の予定に戻す。
Railsの基本にそって、DBに登録して、表示。

**Comment by vestige** [comment]
来週(6/6)あたりにDBの用意、地図情報の登録を行う。

**Comment by vestige** [comment]
https://github.com/vestige/tkbb/wiki/Design

**Comment by vestige** [comment]
scaffoldをためす。7/24に行う。

**Comment by vestige** [comment]
rails g scaffold placement name:string latitude:float longitude:float

**Comment by vestige** [comment]
rake db:migrate

**Comment by vestige** [comment]
なんとなく理解できたので、クローズ！
