### ISSUE TITLE
Google Mapをどういう風に表示するかを決める

### ISSUE THREAD

**Issue by vestige** [vestige/tkbb#7]
どんなライブラリをつかったらいいかとか
どういう風に表示するかなど

**Comment by vestige** [comment]
宿題
- http://ruby-toolbox.com/

**Comment by tatsuosakurai** [comment]
"Google Maps API Web サービス - Google Maps API Web サービス - Google Code" http://code.google.com/intl/ja/apis/maps/documentation/webservices/index.html
このあたりなんすかねえ？

**Comment by tatsuosakurai** [comment]
"RailsプラグインGeokitで位置情報アプリ｜WEBデザイン Tips" 
http://blog.digital-squad.net/article/199200254.html
簡単な説明

**Comment by 1syo** [comment]
ruby-toolbox.comから2つをピックアップしてREADMEを読んでみました
GeoKit-RailsはGeoKit-gemをRailsで利用するものなのでGeokit-Railsをのみを評価してみました。
- GeoKit-Rails
  - http://geokit.rubyforge.org/readme.html
- Geocoder
  - https://github.com/alexreisner/geocoder

両者ともできることはほとんど同じみたい

GeocoderはMongoDBをサポートしている。
MongoDBはgeocode型?なるものがあるとかないとか?(要調査)

MongoDB使うか使わないかが選定のポイントになりそうな予感

**Comment by vestige** [comment]
これはissue 6で実験ができたら終了かな？

**Comment by vestige** [comment]
4sq風なUIまで進んだ。#13 で方針が決定した。
