### ISSUE TITLE
.rvmrc 作る

### ISSUE THREAD

**Issue by tatsuosakurai** [vestige/tkbb#8]

**Comment by tatsuosakurai** [comment]
あ、コミットログにナンバー入れ忘れた；ｘ；

**Comment by vestige** [comment]
これなにに必要なの？

**Comment by tatsuosakurai** [comment]
これ作っておくと、そのディレクトリに移動してきたら、
指定してある gemset を読んでくれるので、複数環境がある人にはとても便利なのです。
でないと、いちいち rvm use hogehoge ってしないと、rails2 の環境で rails s とか打って、s という名前のrailsプロジェクトを生成してしまうのです。（rails3 で言うところの rails new app_name は rails2 だと rails app_name なんです）

**Comment by vestige** [comment]
28日に各PCをチェックする

**Comment by tatsuosakurai** [comment]
僕の勘違いでgemsetは不要。.rvmrcで使うRubyのバージョンだけ書けばよい。
rvm use ruby-1.9.2-p180
.rvmrcは各自で管理することに。→gitの管理外にする

**Comment by vestige** [comment]
rvmインストールし直し。

**Comment by 1syo** [comment]
$ bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)

**Comment by 1syo** [comment]
curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest

**Comment by vestige** [comment]
fatal: could not create work tree dir 'rvm'.: Permission denied

ERROR: Unable to clone the RVM repository, attempted both git:// and https://

**Comment by vestige** [comment]
mac portsを使って，ruby 1.9.1p378にした。
railsのバージョンは3.0.7

**Comment by vestige** [comment]
1.9.2にできました。無事に設定終了。
